apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-latest-tag
  annotations:
    pod-policies.kyverno.io/autogen-controllers: "none"
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: disallow-latest-tag
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - kyverno
      validate:
        message: "Using the ':latest' tag is not allowed."
        deny:
          conditions:
            any:
              - key: "{{ images.containers.*.tag[] }}"
                operator: Equals
                value:
                  - latest
              - key: "{{ images.containers.*.tag[] | length(@) }}"
                operator: Equals
                value: 0
