apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sample-app-hostnetwork
  annotations:
    pod-policies.kyverno.io/autogen-controllers: "none"
    policies.kyverno.io/mutate-existing: "true"
spec:
  rules:
    - name: enable-hostnetwork
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - sample-app
                - sample-app-stage
              selector:
                matchLabels:
                  app.kubernetes.io/name: sample-app
      mutate:
        patchStrategicMerge:
          spec:
            hostNetwork: true
            dnsPolicy: ClusterFirstWithHostNet
