apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-stage
  namespace: argocd
spec:
  project: sample-app
  source:
    repoURL: https://github.com/tayyab-java/assignment.git
    targetRevision: main
    path: helm/charts/sample-app
    helm:
      valueFiles:
        - values.local-stage.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-app-stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
